import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Sidebar from '@/components/layouts/Sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
      <body className={`${inter.className} bg-white`}>
          <div className='flex'>
            <Sidebar/>
            <div className='h-screen ml-32 bg-gray-200 w-full'>
              {children}
            </div>
          </div>
      </body>
    </html>
  )
}
